### ISSUE TITLE
Renaming the folder to gitblame after cloning the repo

### ISSUE THREAD

**Issue by anterabyte** [juliardi/lite-xl-gitblame#1]
Hi @juliardi,

In Readme.md under Installation section, it is mentioned that,

> Clone this repo into your plugins folder, usually LITE_XL_CONFIG_DIR/plugins (in case of linux, this is ~/.config/lite-xl/plugins).

But I have found issues with it that lite-xl does not seem to recognize that plugin untill I rename the cloned folder to gitblame from lite-xl-gitblame.

**Comment by juliardi** [comment]
Ah yes, I forgot to mention that. Thanks for reminding me. I will update the readme file soon.

**Comment by juliardi** [comment]
I have updated the readme file. I hope it is clear enough that user must rename the folder first so Lite XL can recognize this plugin.
